USE [master]
GO

/****** Object:  Database [IARCOD]    Script Date: 11/20/2012 1:07:52 PM ******/
DROP DATABASE [IARCOD]
GO

/****** Object:  Database [IARCOD]    Script Date: 11/20/2012 1:07:52 PM ******/
CREATE DATABASE [IARCOD] ON  PRIMARY 
( NAME = N'IARCOD', FILENAME = N'G:\IARCOD.mdf' , SIZE = 79936192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IARCOD_log', FILENAME = N'G:\IARCOD_log.ldf' , SIZE = 60736000KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [IARCOD] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IARCOD].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [IARCOD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IARCOD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IARCOD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IARCOD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IARCOD] SET ARITHABORT OFF 
GO

ALTER DATABASE [IARCOD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IARCOD] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [IARCOD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IARCOD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IARCOD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IARCOD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IARCOD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IARCOD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IARCOD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IARCOD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IARCOD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IARCOD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IARCOD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IARCOD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IARCOD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IARCOD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IARCOD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IARCOD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IARCOD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [IARCOD] SET  MULTI_USER 
GO

ALTER DATABASE [IARCOD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IARCOD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IARCOD] SET  READ_WRITE 
GO

